name: Scraper Air Corsica

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Chrome profile
        run: cp -R ~/scraper_corse/chrome_profile ./chrome_profile

      - name: Use system Python
        run: python3 --version

      - name: Install dependencies
        run: pip3 install requests pandas plotly

      - name: Run scraper
        run: python3 scraper_aircorsica.py

      - name: Generate dashboard
        run: python3 generate_dashboard.py

      - name: Commit and push results
        run: |
          git config --global user.email "patrice.salini@me.com"
          git config --global user.name "Patrice"
          git add .
          git commit -m "Update Air Corsica data" || echo "Nothing to commit"
          git push
