name: Scraper Air Corsica

on:
  schedule:
    - cron: "0 4 * * *"   # Tous les jours à 04:00
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run scraper
        run: |
          python scraper_aircorsica.py > results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: aircorsica-prices
          path: results.json
